import json
import os
import re
import shutil
from pathlib import Path

from . import util
from .categories import FileSpec, HOME, CONFIG, OMARCHY, STATE

ETC_OMARCHY_CONF = Path("/etc/omarchy.conf")


def _git(repo: Path, *args) -> str:
    return util.run_out(["git", *args], cwd=repo)


def collect_plugins(stage: Path) -> dict:
    plugins_dir = OMARCHY / "plugins"
    meta = {"plugins": []}
    if not plugins_dir.exists():
        return meta
    for plugin_dir in sorted(p for p in plugins_dir.iterdir() if p.is_dir()):
        entry = {"id": plugin_dir.name}
        git_dir = plugin_dir / ".git"
        if git_dir.exists():
            entry["git"] = {
                "remote": _git(plugin_dir, "remote", "get-url", "origin") or None,
                "branch": _git(plugin_dir, "rev-parse", "--abbrev-ref", "HEAD") or None,
                "head": _git(plugin_dir, "rev-parse", "HEAD") or None,
                "dirty": bool(_git(plugin_dir, "status", "--porcelain").strip()),
            }
            patch = _git(plugin_dir, "diff", "HEAD", "--binary")
            if patch:
                entry["patch_archive"] = f"plugins/{plugin_dir.name}.patch"
                (stage / entry["patch_archive"]).write_text(patch)
        dest = stage / "plugins" / plugin_dir.name
        util.copy_tree(plugin_dir, dest, skip_names=(".git",))
        meta["plugins"].append(entry)
    return meta


def import_plugins(stage: Path, backup_root: Path, log: dict | None = None) -> list[str]:
    notes: list[str] = []
    meta_path = stage / "plugins.json"
    plugins_dir = OMARCHY / "plugins"
    if not meta_path.exists():
        return notes
    meta = json.loads(meta_path.read_text())
    for entry in meta.get("plugins", []):
        pid = entry["id"]
        target = plugins_dir / pid
        existed = target.exists()
        if existed:
            util.backup_file(target, backup_root)
            shutil.rmtree(target)
        git_info = entry.get("git") or {}
        cloned = False
        if git_info.get("remote"):
            if util.require_bin("git"):
                plugins_dir.mkdir(parents=True, exist_ok=True)
                clone = util.run(
                    ["git", "clone", "--origin", "origin", git_info["remote"], str(target)],
                    check=False,
                )
                cloned = clone.returncode == 0
                if cloned and git_info.get("head"):
                    util.run(["git", "checkout", git_info["head"]], check=False, cwd=target)
                elif cloned and git_info.get("branch"):
                    util.run(["git", "checkout", git_info["branch"]], check=False, cwd=target)
            else:
                notes.append(f"plugin {pid}: git not available, used bundled copy")
        if not cloned:
            src = stage / "plugins" / pid
            if src.exists():
                util.copy_tree(src, target, skip_names=(".git",))
        patch_archive = entry.get("patch_archive")
        if patch_archive and target.exists() and util.require_bin("git"):
            patch_file = stage / patch_archive
            if patch_file.exists():
                apply = util.run(["git", "apply", "--whitespace=nowarn", str(patch_file)], check=False, cwd=target)
                if apply.returncode == 0:
                    notes.append(f"plugin {pid}: applied local modifications patch")
                else:
                    notes.append(f"plugin {pid}: patch failed to apply cleanly (kept cloned/bundled state)")
        notes.append(f"plugin {pid}: installed")
        if log is not None:
            rel = target.resolve().relative_to(HOME).as_posix()
            log["actions"].append({"action": "overwrite" if existed else "add", "target": rel, "cat": "plugins"})
            if not existed:
                log["added"].append(rel)
    return notes


def collect_packages(stage: Path) -> dict:
    out = util.run_out(["pacman", "-Qm"])
    foreign = []
    for line in out.splitlines():
        if not line.strip():
            continue
        name, _, version = line.partition(" ")
        foreign.append({"name": name, "version": version})
    meta = {"foreign": foreign}
    helper = "paru" if util.require_bin("paru") else ("yay" if util.require_bin("yay") else "AUR_HELPER")
    lines = [
        "#!/bin/bash",
        "# Generated by OmarchyExport - reinstall foreign/AUR packages.",
        "# Review before running. Requires an AUR helper.",
        f'HELPER="{helper}"',
        'if [ "$HELPER" = "AUR_HELPER" ]; then echo "No AUR helper found; install paru or yay first." >&2; exit 1; fi',
        "",
    ]
    names = sorted({p["name"] for p in foreign if not p["name"].endswith("-debug")})
    for chunk_start in range(0, len(names), 20):
        chunk = names[chunk_start : chunk_start + 20]
        lines.append(f'"$HELPER" -S --needed ' + " ".join(chunk) + " || true")
    (stage / "packages-reinstall.sh").write_text("\n".join(lines) + "\n")
    return meta


def import_packages(stage: Path) -> list[str]:
    notes: list[str] = []
    script = stage / "packages-reinstall.sh"
    if script.exists():
        target = HOME / ".local" / "share" / "omarchy-export" / "packages-reinstall.sh"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(script.read_text())
        target.chmod(0o755)
        notes.append(f"package reinstall script saved to {target} (review, then run it yourself)")
    else:
        notes.append("no package list in bundle")
    return notes


def _devlink_checkout() -> Path | None:
    conf_path = ETC_OMARCHY_CONF
    if conf_path.exists():
        text = conf_path.read_text()
        m = re.search(r'OMARCHY_PATH\s*=\s*"([^"]+)"', text)
        if m:
            return Path(os.path.expanduser(m.group(1)))
    env_path = os.environ.get("OMARCHY_PATH")
    if env_path:
        return Path(env_path)
    return None


def collect_devlink(stage: Path) -> dict:
    checkout = _devlink_checkout()
    if not checkout or not (checkout / ".git").exists():
        return {"configured": False}
    remotes = {}
    for line in _git(checkout, "remote", "-v").splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[-1] == "(fetch)":
            remotes[parts[0]] = parts[1]
    meta = {
        "configured": True,
        "etc_omarchy_conf": ETC_OMARCHY_CONF.read_text() if ETC_OMARCHY_CONF.exists() else None,
        "checkout": str(checkout),
        "remotes": remotes,
        "branch": _git(checkout, "rev-parse", "--abbrev-ref", "HEAD") or None,
        "head": _git(checkout, "rev-parse", "HEAD") or None,
    }
    patch = _git(checkout, "diff", "HEAD", "--binary")
    if patch:
        meta["patch_archive"] = "devlink.patch"
        (stage / meta["patch_archive"]).write_text(patch)
    status = _git(checkout, "status", "--porcelain")
    if status:
        meta["uncommitted"] = [l for l in status.splitlines()]
    return meta


def import_devlink(stage: Path) -> list[str]:
    meta_path = stage / "devlink.json"
    if not meta_path.exists():
        return []
    meta = json.loads(meta_path.read_text())
    if not meta.get("configured"):
        return ["devlink: source machine was not dev-linked; nothing to do"]
    share_dir = HOME / ".local" / "share" / "omarchy-export"
    checkout = meta.get("checkout", "~/src/omarchy")
    notes = [
        "devlink: re-creating a dev link is manual by design. Suggested steps:",
        f"  1. git clone {meta.get('remotes', {}).get('origin', '<remote-url>')} {checkout}",
    ]
    if meta.get("head"):
        notes.append(f"  2. git -C {checkout} checkout {meta['head']}")
    patch = stage / "devlink.patch"
    if patch.exists():
        saved = share_dir / "devlink.patch"
        share_dir.mkdir(parents=True, exist_ok=True)
        saved.write_text(patch.read_text())
        notes.append(f"  3. git -C {checkout} apply {saved}  (local modifications from the source machine)")
    notes.append("  4. omarchy dev link <checkout-path>  then reboot")
    return notes


def collect_defaults(stage: Path) -> dict:
    meta = {}
    copied = []
    simple = [
        (OMARCHY / "defaults" / "agent", "defaults/agent"),
        (CONFIG / "xdg-terminals.list", "defaults/xdg-terminals.list"),
        (CONFIG / "mimeapps.list", "defaults/mimeapps.list"),
        (STATE / "current" / "theme.name", "defaults/theme.name"),
    ]
    for src, archive in simple:
        if src.exists():
            util.copy_file(src, stage / archive)
            copied.append(archive)
    toggles = _dir_files_safe(STATE / "toggles", "defaults/toggles")
    for spec in toggles:
        util.copy_file(spec.target, stage / spec.archive)
    if toggles:
        copied.append("defaults/toggles")
    meta["copied"] = copied
    font = util.run_out(["fc-match", "monospace", "-f", "%{family}"])
    meta["font"] = font.split(",")[0].strip() if font else None
    return meta


def _dir_files_safe(base: Path, archive_prefix: str) -> list[FileSpec]:
    specs = []
    if not base.exists():
        return specs
    for p in sorted(base.rglob("*")):
        if p.is_file():
            specs.append(FileSpec(p, f"{archive_prefix}/{p.relative_to(base)}"))
    return specs


def import_defaults(stage: Path, backup_root: Path, log: dict | None = None) -> list[str]:
    notes: list[str] = []
    copies = [
        ("defaults/agent", OMARCHY / "defaults" / "agent"),
        ("defaults/xdg-terminals.list", CONFIG / "xdg-terminals.list"),
        ("defaults/mimeapps.list", CONFIG / "mimeapps.list"),
        ("defaults/theme.name", STATE / "current" / "theme.name"),
    ]
    for archive, target in copies:
        src = stage / archive
        if src.exists():
            existed = target.exists()
            util.backup_file(target, backup_root)
            util.copy_file(src, target)
            if log is not None:
                rel = target.resolve().relative_to(HOME).as_posix()
                log["actions"].append({"action": "overwrite" if existed else "add", "target": rel, "cat": "defaults"})
                if not existed:
                    log["added"].append(rel)
    toggles_src = stage / "defaults" / "toggles"
    if toggles_src.exists():
        toggles_target = STATE / "toggles"
        existed = toggles_target.exists()
        if existed:
            util.backup_file(toggles_target, backup_root)
        util.copy_tree(toggles_src, toggles_target)
        if log is not None:
            rel = toggles_target.resolve().relative_to(HOME).as_posix()
            log["actions"].append({"action": "overwrite" if existed else "add", "target": rel, "cat": "defaults"})
            if not existed:
                log["added"].append(rel)
    meta_path = stage / "defaults.json"
    if meta_path.exists():
        meta = json.loads(meta_path.read_text())
        font = meta.get("font")
        theme_name = None
        theme_file = stage / "defaults" / "theme.name"
        if theme_file.exists():
            theme_name = theme_file.read_text().strip()
        if theme_name:
            notes.append(f"theme: run `omarchy theme set \"{theme_name}\"` to apply (or let OmarchyExport offer it)")
        if font:
            installed = font in util.run_out(["fc-list", ":", "family"]).replace("\\,", ",")
            if installed:
                notes.append(f"font: '{font}' found on this machine - run `omarchy font set \"{font}\"` if desired")
            else:
                notes.append(f"font: '{font}' is NOT installed on this machine; install it first, then `omarchy font set \"{font}\"`")
    return notes


SPECIAL_COLLECTORS = {
    "plugins": collect_plugins,
    "packages": collect_packages,
    "devlink": collect_devlink,
    "defaults": collect_defaults,
}


def collect_special(cid: str, stage: Path) -> dict:
    return SPECIAL_COLLECTORS[cid](stage)
